server:
  port: 8100
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://115.22.206.139:3306/shoppingmallproject?useUnicode=true
    username: root
    password: TestPassword
    
  security:
    user:
      name: test
      password: 1234
    oauth2:
      client:
        registration:
          google:
            client-id: 571579964104-6secbqoe7ulqkpspnffu82mamcb7pt3e.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          naver:
            client-id: L83YgZR6VcBrrpdZtpkU
            client-secret: a4tsasp8uL
            scope:
            - email
            - name 
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8100/login/oauth2/code/naver
        provider:
          naver: 
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json으로 가지고 올 때 response라는 key값으로 데이터를 전달

mybatis:
  mapper-locations:
  - /mappers/*.xml